### PR TITLE
fix: mark old parent dirty when necessary

### LINKED ISSUE #32: Introduce setParent() API to AbstractComponent
When doing so, as a follow up for #21, the following legacy FW unit test should be added and pass

```java
    @Test
    public void setParent_marks_old_parent_as_dirty() {
        HasComponents hasComponents = Mockito.mock(HasComponents.class);
        TestComponent testComponent = new TestComponent();
        testComponent.setParent(hasComponents);
        testComponent.setParent(null);
        Mockito.verify(hasComponents, Mockito.times(1)).markAsDirty();
    }
```

### PR DESCRIPTION
**Pull request by pleku**
Introduces setParent to AbstractComponent, with the role of only setting the
old parent, if any, as dirty.

Fixes #32

### CODE REVIEW

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponent.java [hunk 1]
```diff
@@ -72,6 +74,31 @@ public void beforeClientResponse(boolean initial) {
...
     }
 
+    /**
+     * Sets the parent legacy component of the component. The role of this
+     * method is to just make sure the old parent is flagged as dirty so that
+     * changes are applied (e.g. to sizing).
+     *
+     * @param parent
+     *            the parent connector
+     * @throws IllegalStateException
```
Comment (DiegoCardoso) [inline vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponent.java:84]: This doesn't seem right. The FW implementation does throw an `IllegalStateException` on such case, but I can't see it here.

**Review by DiegoCardoso — CHANGES_REQUESTED** [review]

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponent.java (hunk 1 above)
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponent.java:84]: The likelihood of someone relying this to throw is probably quite slim as this is supposed to be a FW internal method but added it here. It might cause actually issues if some legacy component does something in a funky way, but should be easy to catch

**Review by DiegoCardoso — APPROVED** [review]
