### PR TITLE
fix: not use components for AbsOrdLayout internals

### LINKED ISSUE #42: Refactor AbstractOrderedLayout to not use components for internal parts
Because the internal parts of the HL+VL are built with components (`Div`), the following code snippet is problematic
```
VerticalLayout layout = new VerticalLayout();
Button button = new Button():
layout.addComponent(button);

button.getParent(); // For V7, V8 and V10+, this would return VerticalLayout (wrapped in optional since v10)
```
For the legacy HL+VL, it will return the internal `Div` for the slot instead, which is problematic/broken.

Since there is no good reason for using components internally, usage of those should be avoided and just stick to elements + temporary component instances instead.

### PR DESCRIPTION
**Pull request by pleku**
Uses elements instead and removes extra bookkeeping with components.
To handle removing of children properly, also uses detach listeners
to make sure removal of children cleans up extra slots.

Fixes #42, #39

### CODE REVIEW

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java [hunk 1]
```diff
@@ -58,20 +62,50 @@ public AbstractOrderedLayout() {
...
     @Override
     public void addComponent(Component component) {
-        if (!components.containsKey(component)) {
-            Div slot = wrapInSlot(component);
-            addSlot(slot);
-            components.put(component, slot);
-        }
+        Element container = expandWrapper == null ? getElement()
+                : expandWrapper;
+        component.getParent().ifPresent(parentComponent -> {
```
Comment (fhdhsni) [inline vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:76]: nit: might be a bit more clear to do it without "get parent component if present"

```
Element possibleSlot = component.getElement().getParent();
component.getElement().removeFromParent();

// handle special case of adding an existing child again
if (possibleSlot != null && container.equals(possibleSlot.getParent())) {
    possibleSlot.removeFromParent();
}
```

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java [hunk 2]
```diff
@@ -58,20 +62,50 @@ public AbstractOrderedLayout() {
...
+            if (container.equals(oldParent.getParent())) {
+                oldParent.removeFromParent();
+            }
+        });
+
+        container.appendChild(wrapInSlot(component));
+        // one-time detach listener added for clearing the slot always
+        AtomicReference<Registration> holder = new AtomicReference<>();
+        holder.set(component.getElement().addDetachListener(event -> {
+            cleanupEmptySlots();
```
Comment (fhdhsni) [inline vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:89]: we can just `markAsDirty` to avoid calling `cleanupEmptySlots` unnecessarily, when many children are removed in one go

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java [hunk 3]
```diff
@@ -122,44 +156,33 @@ public void setWidth(String width) {
...
+                        && component.getParent().get() == this)
+                .forEach(component -> {
+                    final Element element = component.getElement();
+                    element.getParent().removeFromParent(); // cleanup slot
+                                                            // eagerly
+                    // TODO remove spacing
+                    element.removeFromParent();
+                });
+        if (container.getChildCount() != childCount) {
+            cleanupEmptySlots();
```
Comment (fhdhsni) [inline vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:178]: same as before, just calling `makeAsDirty`.

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java (hunk 1 above)
Comment (fhdhsni) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:76]: can't we just call this?
```
component.getElement().removeFromParent();
```
there will be an empty slot but make as dirty will take care of it.

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java [hunk 4]
```diff
@@ -122,44 +156,33 @@ public void setWidth(String width) {
...
+        // legacy behavior for non-children is NOOP (different from flow)
 
-            Div slot = this.components.get(component);
-            this.components.remove(component);
-            removeSlot(slot);
+        Arrays.stream(components)
+                .filter(component -> component.getParent().isPresent()
+                        && component.getParent().get() == this)
+                .forEach(component -> {
+                    final Element element = component.getElement();
```
Comment (fhdhsni) [inline vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:171]: same as before, we can just call
```
Arrays.stream(components)
        .filter(component -> component.getParent().isPresent()
                && component.getParent().get() == this)
        .forEach(component -> {
            component.getElement().removeFromParent();
            markAsDirty();
        });
```

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java (hunk 3 above)
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java]: I've refactored the logic, not applicable anymore

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java (hunk 2 above)
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java]: I've refactored the logic, not applicable anymore

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java (hunk 1 above)
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java]: Refactored.

I'd cleanup the slots as eagerly as possible as leaving those dangling could compromise any other operations, unless those call "cleanup" every single time before doing something. markAsDirty is just for fail-safe that empty slots should not be left when response is written to client side (and for other things too).

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java [hunk 5]
```diff
@@ -58,20 +62,50 @@ public AbstractOrderedLayout() {
...
+
     @Override
     public void addComponent(Component component) {
-        if (!components.containsKey(component)) {
-            Div slot = wrapInSlot(component);
-            addSlot(slot);
-            components.put(component, slot);
-        }
+        Element container = expandWrapper == null ? getElement()
+                : expandWrapper;
```
[the remark this answers is not in the document]
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java]: Done

File: vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java (hunk 4 above)
Comment (pleku) [reply vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java:168]: Not applicable / slots should be cleaned up eagerly

**Review by fhdhsni — APPROVED** [review]

**Review by DiegoCardoso — APPROVED** [review]
